# Header
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives


# Default post title
default_post_title: Untitled

# Default post cover index page
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page
default_cover_detail: "http://placehold.it/1300x500"

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: funfrolic
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
facebook_url: https://www.facebook.com/Fun-Frolic-Photography-1755765351324326/?fref=ts
twitter_url: /
googleplus_url: /
behance_url: /
rss_url:
